import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import AppContextProvider from "@/context/AppContext";
import { ThemeProvider } from "next-themes";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Smart AI - App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <AppContextProvider>
        <html lang="en" suppressHydrationWarning>
          <body className={`${inter.className} antialiased transition-colors duration-300`}>
            <Toaster toastOptions={
              {
                success: { style: { background: "black", color: "white" } },
                error: { style: { background: "black", color: "white" } }
              }
            }
            />
            <ThemeProvider attribute="class" enableSystem defaultTheme="system">
              {children}
            </ThemeProvider>
          </body>
        </html>
      </AppContextProvider>
    </ClerkProvider>
  );
}
